name: Record progress

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m')"

      - name: Create Release
        id: nightly-snapshot
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: ${{ steps.date.outputs.date }}
          draft: true
          body: |
            # Description:
            ### This is a record of my progress from 2021. I'm planning to create a release every two-to-three months.

            #### Note: I actually started programming in 2018 with PHP but got into programming seriously in 2019 and many things are not recorded here.
